### ISSUE TITLE
Most people won't be able to add labels to issues

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/toolbox#13]
In the [wiki](https://github.com/theodi/toolbox/wiki/How-to-Contribute-to-the-ODI-Toolbox#file-an-issue-for-resolution) it is suggested that contributors add labels to their new issues however I don't think they'll have [the rights](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/) to do that.

**Comment by quadrophobiac** [comment]
Thanks for catching this Stephen - I assumed it was possible purely because I am only au fait with my own GH experience with repository access privileges. The erroneous text has been excised
