### ISSUE TITLE
How do you tag a repository administrator?

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/toolbox#14]
The [wiki](https://github.com/theodi/toolbox/wiki/Contributing-Code) says to ask about contributing, "by tagging a repository administrator on the issue ticket".

How do you know who is the repository administrator? If this is a GitHub page, provide a link.

**Comment by quadrophobiac** [comment]
I think I wrote this after reading about the github code owners link you shared. As this is not yet a feature of the toolbox - nor is it easily declared - and won't be for foreseeable I am going to remove all references to this

**Comment by Stephen-Gates** [comment]
@quadrophobiac here's how I tagged the repository admins on Data Curator https://github.com/ODIQueensland/data-curator/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Not elegant but FYI
