### ISSUE TITLE
Add Octobox to the Toolbox 

### ISSUE THREAD

**Issue by Stephen-Gates** [theodi/toolbox#23]
### Desired Behaviour (for enhancement suggestions only)

Add rights for Octobox to monitor the 6 apps in the toolbox

> If you manage more than one active project on GitHub, you probably find GitHub Notifications pretty lacking.
> 
> Notifications are marked as read and disappear from the list as soon as you load the page or view the email of the notification. This makes it very hard to keep on top of which notifications you still need to follow up on. Most open source maintainers and GitHub staff end up using a complex combination of filters and labels in Gmail to manage their notifications from their inbox. If, like me, you try to avoid email, then you might want something else.
> 
> Octobox adds an extra "archived" state to each notification so you can mark it as "done". If new activity happens on the thread/issue/pr, the next time you sync the app the relevant item will be unarchived and moved back into your inbox.
>

https://github.com/octobox/octobox

**Comment by Floppy** [comment]
I tried Octobox a while back, and it is enabled/approved on theodi organisation, so this should work already for toolbox repos. As far as I can tell.

**Comment by Stephen-Gates** [comment]
Thanks @Floppy 
I can see Certificates but not others

**Comment by Floppy** [comment]
Oh, odd. I'll dig in.

**Comment by Floppy** [comment]
Wierdly, I don't see *anything* in Octobox at all, never have. And there aren't any other settings I can tweak. Do you have it working on other orgs?

**Comment by Stephen-Gates** [comment]
I see this in Octobox settings

<img width="761" alt="screenshot 2017-10-05 22 58 16" src="https://user-images.githubusercontent.com/9379524/31228422-d7bd267c-aa20-11e7-9fb4-08e0de00c51f.png">

**Comment by Floppy** [comment]
Same - I'm not sure what else there is to change...

**Comment by Stephen-Gates** [comment]
I can see across the Frictionless Data repos
<img width="1248" alt="screenshot 2017-10-05 23 00 59" src="https://user-images.githubusercontent.com/9379524/31228529-350115be-aa21-11e7-9b2e-70eaecb4cf1e.png">

**Comment by Floppy** [comment]
That's really odd. I wonder if @andrew knows what it could be?

**Comment by Stephen-Gates** [comment]
Appears to be working across repos
