### ISSUE TITLE
indicate alpha/beta/live status on toolbox

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/toolbox#3]
landing page (text or image overlay) and per page of tool
data publishing tools
* Octopub: Beta
* Bothan: ~~Alpha~~ Beta
* Comma Chameleon: Alpha
* CSVlint: Beta/Live
* CSVHub: Alpha

Open source, ODI Branded services
* Pathway: Live
* Certificates: Live

**Comment by Floppy** [comment]
I think Bothan could be beta, now.
