### ISSUE TITLE
Bundle install breaks due to json 1.8.3

### ISSUE THREAD

**Issue by quadrophobiac** [theodi/toolbox#5]
could this be remedied by updating dependencies

**Comment by Floppy** [comment]
Yes, 1.8.3 doesn't work on Sierra. bundle update `json` and perhaps `eventmachine` is normally needed.

**Comment by quadrophobiac** [comment]
because this was sierra specific I just updated the json to run locally but didn't amend the repo's gemfile

**Comment by Floppy** [comment]
No harm in updating it anyway.
